### ISSUE TITLE
When are we supposed to deliver the MarketMaker?

### ISSUE THREAD

**Issue by pedrocunial** [raulikeda/Backtesting#7]
Hey there @raulikeda!

I was wondering alongside @marcelogdeandrade when should we deliver the Market Maker version of the project. I thought it was supposed to be made until this friday, however I just could not find any documentation about it.

Thank you,

pedrocunial

**Comment by marcelogdeandrade** [comment]
I'm not sure if this project is divided in two releases:

1. Implementing PBR calculation and creating two orders for each event based on this value.
2. Implement the fill method simulating an agressive move on an order.

My understanding was that the first release should be delivered on May 24th, an the second one at the end of the semester, probably on June.

@raulikeda, Could you clarify the handover dates?

With appreciation,
Marcelo

**Comment by GabrielValeRios** [comment]
@raulikeda already clarified the dates in class, and not sure if this is an issue per say. Please, pay more attention in class and stop fooling around this repo. Thanks.

**Comment by MatheusDMD** [comment]
Hello @pedrocunial & @marcelogdeandrade !
I was also wondering the same thing.

I carefully checked all class documentation on the this discipline's Blackboard section. please refer to the class documentation but found nothing regarding the delivery dates.

@raulikeda, if you could please update the project documentation. That would be of great use.

Best,
Matheus

**Comment by raulikeda** [comment]
Pra acabar com a discussão. A princípio eu tinha colocado no quadro da aula que poderiam entregar no dia 03/Jun. Junto com a apresentação final do projeto do Blockchain. Tanto o Market maker quanto a calculadora de VaR.
